[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
healthcheckPath = "/health/liveliness"
healthcheckTimeout = 300

[[services]]
name = "litellm"

[services.env]
PORT = "4000"
