name: Build and Push Docker Image

on:
  push:
    branches:
      - '**'  # Trigger on all branches
  pull_request:
    branches:
      - '**'  # Also trigger on PRs for testing

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Branch name (lowercase)
            type=ref,event=branch,suffix={{branch}}
            # Short SHA for commits
            type=sha,prefix={{branch}}-
            # Latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Generate lowercase branch tag
        id: tags
        run: |
          # Get branch name and convert to lowercase
          BRANCH_NAME="${{ github.ref_name }}"
          LOWERCASE_BRANCH=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/-/g')
          
          # Generate tags
          TAGS="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${LOWERCASE_BRANCH}"
          
          # Add SHA tag
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TAGS="${TAGS},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${LOWERCASE_BRANCH}-${SHORT_SHA}"
          
          # Add latest tag if this is the default branch
          if [[ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]]; then
            TAGS="${TAGS},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
          fi
          
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "branch=${LOWERCASE_BRANCH}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: |
            org.opencontainers.image.title=${{ github.repository }}
            org.opencontainers.image.description=LiteLLM Proxy Server with Stripe Integration
            org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ steps.tags.outputs.branch }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image details
        run: |
          echo "Built and pushed images:"
          echo "${{ steps.tags.outputs.tags }}" | tr ',' '\n' | while read tag; do
            echo "  - ${tag}"
          done
          echo ""
          echo "Pull command:"
          echo "  docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.branch }}"